# Generated by Django 2.2.5 on 2020-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongLysic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=64, unique=True, verbose_name='歌曲ID')),
                ('song_lysic', models.TextField(blank=True, verbose_name='歌词')),
            ],
            options={
                'verbose_name_plural': '歌词信息',
                'db_table': 'songLysic',
            },
        ),
        migrations.CreateModel(
            name='SongSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(blank=True, max_length=64, verbose_name='歌曲ID')),
                ('sim_song_id', models.CharField(blank=True, max_length=64, verbose_name='相似歌曲ID')),
                ('sim', models.FloatField(blank=True, verbose_name='相似度')),
            ],
            options={
                'verbose_name_plural': '歌曲相似',
                'db_table': 'SongSim',
            },
        ),
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=64, verbose_name='歌曲ID')),
                ('tag', models.CharField(blank=True, max_length=64, verbose_name='歌曲标签')),
            ],
            options={
                'verbose_name_plural': '歌曲标签',
                'db_table': 'SongTag',
            },
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_lysic',
        ),
        migrations.AlterField(
            model_name='song',
            name='song_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='歌曲名字'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_pl_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='专辑ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_sing_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='歌手ID'),
        ),
    ]
