# Generated by Django 2.2.5 on 2020-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBrowse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='用户名')),
                ('click_id', models.CharField(blank=True, max_length=64, verbose_name='ID')),
                ('click_cate', models.CharField(blank=True, max_length=64, verbose_name='类别')),
                ('user_click_time', models.DateTimeField(blank=True, verbose_name='浏览时间')),
                ('desc', models.CharField(blank=True, default='Are you ready!', max_length=1000, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '用户行为信息',
                'db_table': 'UserBrowse',
            },
        ),
        migrations.CreateModel(
            name='UserPlayListRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=64, verbose_name='用户ID')),
                ('related', models.CharField(blank=True, max_length=64, verbose_name='歌单ID')),
                ('sim', models.FloatField(blank=True, verbose_name='相似度')),
            ],
            options={
                'verbose_name_plural': '用户歌单推荐',
                'db_table': 'UserPlayListRec',
            },
        ),
        migrations.CreateModel(
            name='UserSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=64, verbose_name='用户ID')),
                ('sim_user_id', models.CharField(blank=True, max_length=64, verbose_name='相似用户ID')),
                ('sim', models.FloatField(blank=True, verbose_name='用户相似度')),
            ],
            options={
                'verbose_name_plural': '用户相似',
                'db_table': 'UserSim',
            },
        ),
        migrations.CreateModel(
            name='UserSingRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=64, verbose_name='用户ID')),
                ('related', models.CharField(blank=True, max_length=64, verbose_name='歌手ID')),
                ('sim', models.FloatField(blank=True, verbose_name='相似度')),
            ],
            options={
                'verbose_name_plural': '用户歌手推荐',
                'db_table': 'UserSingRec',
            },
        ),
        migrations.CreateModel(
            name='UserSongRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=64, verbose_name='用户ID')),
                ('related', models.CharField(blank=True, max_length=64, verbose_name='歌曲ID')),
                ('sim', models.FloatField(blank=True, verbose_name='相似度')),
            ],
            options={
                'verbose_name_plural': '用户歌曲推荐',
                'db_table': 'UserSongRec',
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64, verbose_name='用户ID')),
                ('tag', models.CharField(blank=True, max_length=64, verbose_name='用户标签')),
            ],
            options={
                'verbose_name_plural': '用户标签',
                'db_table': 'UserTag',
            },
        ),
        migrations.CreateModel(
            name='UserUserRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=64, verbose_name='用户ID')),
                ('related', models.CharField(blank=True, max_length=64, verbose_name='用户ID')),
                ('sim', models.FloatField(blank=True, verbose_name='相似度')),
            ],
            options={
                'verbose_name_plural': '用户用户推荐',
                'db_table': 'UserUserRec',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='u_birthday',
            field=models.DateTimeField(blank=True, verbose_name='生日'),
        ),
    ]
