# Generated by Django 2.2.5 on 2020-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayListToSongs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_id', models.CharField(blank=True, max_length=64, verbose_name='歌单ID')),
                ('song_id', models.CharField(blank=True, max_length=64, verbose_name='歌曲ID')),
            ],
            options={
                'verbose_name_plural': '歌曲所属歌单',
                'db_table': 'playListToSongs',
            },
        ),
        migrations.CreateModel(
            name='PlayListToTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_id', models.CharField(blank=True, max_length=64, verbose_name='歌单ID')),
                ('tag', models.CharField(blank=True, max_length=64, verbose_name='歌单标签')),
            ],
            options={
                'verbose_name_plural': '歌单标签',
                'db_table': 'playListToTag',
            },
        ),
    ]
