# Generated by Django 2.2.5 on 2020-04-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingSim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sing_id', models.CharField(blank=True, max_length=64, verbose_name='歌手ID')),
                ('sim_sing_id', models.CharField(blank=True, max_length=64, verbose_name='相似歌手ID')),
                ('sim', models.FloatField(blank=True, verbose_name='相似度')),
            ],
            options={
                'verbose_name_plural': '歌手相似',
                'db_table': 'SingSim',
            },
        ),
        migrations.CreateModel(
            name='SingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sing_id', models.CharField(max_length=64, verbose_name='歌手ID')),
                ('tag', models.CharField(blank=True, max_length=64, verbose_name='歌手标签')),
            ],
            options={
                'verbose_name_plural': '歌手标签',
                'db_table': 'SingTag',
            },
        ),
        migrations.AlterField(
            model_name='sing',
            name='sing_album_num',
            field=models.IntegerField(blank=True, verbose_name='专辑数目'),
        ),
        migrations.AlterField(
            model_name='sing',
            name='sing_music_num',
            field=models.IntegerField(blank=True, verbose_name='音乐数目'),
        ),
        migrations.AlterField(
            model_name='sing',
            name='sing_mv_num',
            field=models.IntegerField(blank=True, verbose_name='MV数目'),
        ),
        migrations.AlterField(
            model_name='sing',
            name='sing_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='歌手名字'),
        ),
    ]
